AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application with lamda function and layer

Parameters:
  Loglevel:
      Description: 'specify log level'
      Type: String
      AllowedValues:
        - DEBUG
        - INFO
      Default: DEBUG
  Env:
    Description: 'specify environment'
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

Conditions:
  IsProd: !Equals [!Ref 'Env', 'prod']
  IsNotProd: !Equals [!Ref 'Env', 'dev']


Resources:
  ######################################################################################################################
  # Layer with build capabilities, automatically execute pip install -r requirements.txt -t installing libraries
  ######################################################################################################################
  commonLibrary:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: commonLibrary
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9 # this is where magic happen, sam build command will read requirements.txt file and download libraries

  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          - arn:aws:iam::aws:policy/AmazonS3FullAccess

  OverviewApiProd:
    Type: AWS::Serverless::Api
    Condition: IsProd
    Properties:
      Name: sam-fowo-prod
      StageName: !Ref Env
      MethodSettings:
        - ResourcePath: /profile
          HttpMethod: POST


  OverviewApiDev:
    Type: AWS::Serverless::Api
    Condition: IsNotProd
    Properties:
      Name: sam-fowo-dev
      StageName: !Ref Env
      MethodSettings:
        - ResourcePath: /profile
          HttpMethod: POST

  ######################################################################################################################
  # Lambda function using MyLayer and MyLibLayer
  ######################################################################################################################
  overviewFunctionProd:
    Type: AWS::Serverless::Function
    Condition: IsProd
    Properties:
      CodeUri: asset_overview/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref commonLibrary
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /profile
            Method: post
            RestApiId:
              Ref: OverviewApiProd

  overviewFunctionDev:
    Type: AWS::Serverless::Function
    Condition: IsNotProd
    Properties:
      CodeUri: asset_overview/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref commonLibrary
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /profile
            Method: post
            RestApiId:
              Ref: OverviewApiDev

  fowoImportRPACSVDev:
    Type: AWS::Serverless::Function
    Condition: IsNotProd
    Properties:
      CodeUri: import_data/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 360
      Layers:
        - !Ref commonLibrary
      Role: !GetAtt LambdaExecutionRole.Arn
  version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref fowoImportRPACSVDev
      Description: v0



